/*
    ShadeQuest/RISStatistics ～ユーザーを作成するためのＳＱＬ文～

    CREATE USER <ユーザー名> IDENTIFIED BY <パスワード>
      DEFAULT TABLESPACE <データ領域>
      TEMPORARY TABLESPACE <テンポラリ領域>
      PROFILE DEFAULT;
    GRANT <権限、ロール> TO <ユーザー名>;

*/
spool CreateUser.log

CREATE USER ikou IDENTIFIED BY ikou1
  DEFAULT TABLESPACE MRMS_DATA
  TEMPORARY TABLESPACE MRMS_TEMP
  PROFILE DEFAULT;

GRANT RECOVERY_CATALOG_OWNER TO IKOU;
GRANT RESOURCE TO IKOU;
GRANT SELECT ANY DICTIONARY TO IKOU;
GRANT DBA TO IKOU;
GRANT SELECT ANY TABLE TO IKOU;
GRANT SELECT ANY TABLE,UPDATE ANY TABLE,DELETE ANY TABLE,INSERT ANY TABLE TO IKOU;
GRANT EXECUTE ANY PROCEDURE to IKOU;
GRANT DROP ANY PROCEDURE to IKOU;
GRANT CREATE ANY PROCEDURE to IKOU;
spool off
QUIT;
